[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core>=1" ]

[tool.poetry]
name = "requirements-detector"
version = "1.6.0"
description = "Python tool to find and list requirements of a Python project"
license = "MIT"
authors = [ "Landscape.io <code@landscape.io>" ]
readme = "README.md"
homepage = "https://github.com/landscapeio/requirements-detector"
keywords = [ "python", "requirements detector" ]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Unix",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Quality Assurance",
]
packages = [
  { include = "requirements_detector/" },
]
include = [
  "c2cgeoform/py.typed",
]
dependencies.python = ">=3.10,<4.0"
dependencies.astroid = "^4.0"
dependencies.packaging = ">=21.3"
dependencies.semver = "^3.0.0"
dependencies.tomli = { version = "^2.2.1", python = "<3.11" }
group.dev.dependencies.coverage = "^5.5"
group.dev.dependencies.pre-commit = "^4.2.0"
group.dev.dependencies.pytest = "^6.2.4"
group.dev.dependencies.pytest-benchmark = "^3.4.1"
group.dev.dependencies.pytest-cov = "^2.12.1"
group.dev.dependencies.tox = "^3.24.5"
group.dev.dependencies.twine = "^6.1.0"
scripts.detect-requirements = "requirements_detector.run:run"
